Wasm `prepare()` doc
anonklub/docs pull request #17
Opened 2024-08-19 15:21 UTC by 0xisk

Separating `prepare()` function in wasm page.

2024-08-20 06:35 UTC, sripwoud requested changes
overall ACK

Just left some suggestions to wrap `prepare` in backticks everywhere

2024-08-20 06:35 UTC, sripwoud commented on docs/prove/wasm.md
> +This setup ensures that any runtime errors in the Rust code are clearly reported, with detailed stack traces available in the console, enhancing the debugging process during development.
haha good you are documenting this, I didn't know myself what the panic_hook was for this purpose!

2024-08-20 06:35 UTC, sripwoud commented on docs/prove/wasm.md
> +For both the `halo2` and `spartan` proving systems, web workers function similarly at the ABI level. To begin importing and initializing the Wasm code in the browser, you should invoke worker.prepare
```suggestion
For both the `halo2` and `spartan` proving systems, web workers function similarly at the ABI level. To begin importing and initializing the Wasm code in the browser, you should invoke `worker.prepare()`. This function handles the necessary steps to load and configure the Wasm module.
```

2024-08-20 06:35 UTC, sripwoud commented on docs/prove/wasm.md
> +The same prepare function is also available in the Merkle tree packages associated with each proving system: `@anonklub/halo2-binary-merkle-tree-worker` for the halo2 circuit and `@anonklub/merkle-tr
```suggestion
The same `prepare` function is also available in the Merkle tree packages associated with each proving system: `@anonklub/halo2-binary-merkle-tree-worker` for the halo2 circuit and `@anonklub/merkle-tree-worker` for the spartan circuit. This ensures consistent Wasm initialization and error reporting across different components of the proving systems.
```

2024-08-20 06:35 UTC, sripwoud commented on docs/prove/wasm.md
> +## Implementation Details of the prepare Function
```suggestion
## Implementation Details of the `prepare` Function
```

2024-08-20 06:35 UTC, sripwoud commented on docs/prove/wasm.md
> +Each package has its own specific implementation of the prepare function, tailored to its particular needs:
```suggestion
Each package has its own specific implementation of the `prepare` function, tailored to its particular needs:
```

2024-08-27 09:59 UTC, 0xisk commented
> overall ACK
> 
> Just small requests for changes:
> 
>     * I suggest wrapping `prepare` in backticks everywhere
> 
>     * can you add a part about using the web workers in react with our custom `useWorker` hook
>       e.g we can write something like this no (the same `useWorker` hook works for all workers right)? Then just refer/link to that part in the necessary section of the halo2 and spartan pages.
>       ```ts
>       import { SpartanEcdsaWorker } from '@anonklub/spartan-ecdsa-worker'
>       import { MerkleTreeWorker } from '@anonklub/merkle-tree-worker'
>       import { Halo2EthMembershipWorker } from '@anonklub/halo2-eth-membership-worker'
>       
>       type Worker =
>         | typeof SpartanEcdsaWorker
>         | typeof MerkleTreeWorker
>         | typeof Halo2EthMembershipWorker
>       
>       export const useWorker = (worker: Worker) => {
>         const [isWorkerReady, setIsWorkerReady] = useState(false)
>       
>         useEffect(() => {
>           void (async () => {
>             await worker.prepare()
>             setIsWorkerReady(true)
>           })()
>         }, [])
>       
>         return isWorkerReady
>       }
>       ```

That is updated, could you check please?

2024-08-27 14:20 UTC, sripwoud requested changes
some final request for changes about the formatting. (you can check how it renders with `pnpm serve`)
Content is good :+1:

2024-08-27 14:20 UTC, sripwoud commented on docs/prove/wasm.md
> +For both the `halo2` and `spartan` proving systems, web workers function similarly at the ABI level. To begin importing and initializing the Wasm code in the browser, you should invoke worker.prepare
```suggestion
For both the `halo2` and `spartan` proving systems, web workers function similarly at the ABI level. To begin importing and initializing the Wasm code in the browser, you should invoke `worker.prepare()`. This function handles the necessary steps to load and configure the Wasm module.
```

2024-08-27 14:20 UTC, sripwoud commented on docs/prove/wasm.md
> +```ts
```suggestion
```js
```

i know it is ts code, but docsify does not support a specific parser for typescript, so this code block will be rendered without syntax highlighting.
If we use `js` then we will have syntax highlighting.

![image](https://github.com/user-attachments/assets/e7b731c9-f9bd-4711-a97e-be61062d9fc3)
vs
![image](https://github.com/user-attachments/assets/70bf0342-d779-49bb-b01d-05a20d150f59)

2024-08-27 14:20 UTC, sripwoud commented on docs/prove/wasm.md
> +```ts
```suggestion
```js
```

2024-08-27 14:20 UTC, sripwoud commented on docs/prove/wasm.md
> +```ts
```suggestion
```js
```

2024-08-27 14:20 UTC, sripwoud commented on docs/prove/wasm.md
> +```ts
```suggestion
```js
```

2024-08-27 14:20 UTC, sripwoud commented on docs/prove/wasm.md
> +```ts
```suggestion
```js
```

2024-08-30 12:41 UTC, 0xisk commented on docs/prove/wasm.md
> +```ts
I am able to see syntax highlighted in this doc for example: https://github.com/anonklub/docs/blob/docs/wasm/docs/prove/wasm.md
Is it not shown in your end?!

2024-08-30 12:58 UTC, 0xisk commented on docs/prove/wasm.md
> +```ts
My bad I didn't think of that.

2024-08-30 13:00 UTC, 0xisk commented on docs/prove/wasm.md
> +```ts
Done.

2024-08-30 13:02 UTC, sripwoud approved these changes
ACK

2024-08-30 13:03 UTC, merged